return {
["START GAME"]="开始游戏",
["NAME: LILY ROSEMARIE HAMILTON"]="姓名：莉莉•络丝玛丽•海尔明顿",
["HEARTRATE: "]="心率：",
["START HOSPTIAL GAMEPLAY DEMO"]="医院关卡演示",
["RESUME GAME"]="继续游戏",
["GENDER: FEMALE"]="性别：女",
["HOSPITALIZED SINCE: JUL 1, 2012"]="住院日期：2012年7月1日",
["BLOOD PRESSURE: %d/%d mmHg"]="血压：%d/%d毫米汞柱",
["DATE OF BIRTH: DEC/16/1993"]="出生日期：1993年12月16日",
["RACE: CAUCASIAN"]="种族：高加索人种",
["RESTART FROM LAST CHECKPOINT"]="从上一个检查点继续",
["str"]="",
["STATUS: COMA"]="状态：昏迷",
["Path of Eternity Priviledge Zero // frame time: %.2fms (%d fps)."]="永恒历程：零权 // 帧率：%.2f毫秒 (每秒%d 帧)",
["DATE: JUL 11, 2012"]="日期：2012年7月11日",
["EXIT TO OPERATION SYSTEM"]="退出到操作系统",
["QUIT GAME"]="退出游戏",
["HEIGHT: 1.60 M"]="身高：1.60米",
}
