require 'ai.aibase'
require 'ai.aihost'
require 'ai.moveto'
require 'ai.stop'
require 'ai.path'
require 'ai.findpath'
require 'ai.wait'
require 'ai.turn'
require 'ai.exposure'
require 'ai.interact'
require 'ai.facing'

require 'ai.guard.patrol'
require 'ai.guard.investigate'
require 'ai.guard.guard'